version: "3"
services:
  lb:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server/load_balancer/nginx.debug.conf:/etc/nginx/nginx.conf:ro
      - ./server/load_balancer/mime.types:/etc/nginx/mime.types
      - ./server/dev_certs:/etc/nginx/ssl/hiveapp
    depends_on:
      - webapp
    networks:
      - lb_net

  webapp:
    build: .
    ports:
      - "3000"
    networks:
      - lb_net

networks:
  lb_net:
