version: '2'
services:
  lb:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server/load_balancer/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./server/dev_certs:/etc/nginx/ssl/hiveapp
    depends_on:
      - webapp
    networks:
      - lb_net
  webapp:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./server:/go/src/letstalk/server
    depends_on:
      - db
    networks:
      - db_net
      - lb_net
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=uwletstalk
      - MYSQL_DATABASE=letstalk
      - MYSQL_USER=letstalk
      - MYSQL_PASSWORD=uwletstalk
    networks:
      - db_net
    ports:
      - "3306:3306"
volumes:
  dbdata:
networks:
  db_net:
  lb_net:
