version: '3'
services:
  webapp:
    build: .
    ports:
      - "3000"
    volumes:
      - ./server:/go/src/letstalk/server
    depends_on:
      - db
    networks:
      - db_net
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=uwletstalk
      - MYSQL_DATABASE=letstalk
      - MYSQL_USER=letstalk
      - MYSQL_PASSWORD=uwletstalk
    networks:
      - db_net
    ports:
      - "3306:3306"
  chat:
    build:
      context: chat/docker/tinode
      args:
        VERSION: 0.15.2
        TARGET_DB: mysql
    container_name: chat-server
    depends_on:
      - db
    networks:
      - db_net
    ports:
      - 6000:18080
      - 7000:16061
volumes:
  dbdata:
networks:
  db_net:
