version: '3'
services:
  webapp:
    build: .
    ports:
      - "3000"
    volumes:
      - ./server:/go/src/letstalk/server
    depends_on:
      - db
      - elasticsearch
    networks:
      - db_net
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=uwletstalk
      - MYSQL_DATABASE=letstalk
      - MYSQL_USER=letstalk
      - MYSQL_PASSWORD=uwletstalk
    networks:
      - db_net
    ports:
      - "3306:3306"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dbdata:/var/lib/elasticsearch/data
    networks:
      - db_net
    ports:
      - "9200:9200"
volumes:
  dbdata:
networks:
  db_net:
