# THIS IS COMMON BETWEEN PROD AND DEBUG

# Create the environment needed for the application
FROM ubuntu:18.04 as env
MAINTAINER Andrew Codispoti

# nodejs repo setup
RUN wget -qO- https://deb.nodesource.com/setup_8.x | sudo -E bash -

# yarn repo setup
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update --fix-missing -y
RUN apt-get install -y vim curl golang git python3 jq nodejs build-essential yarn

# gopath in root
ENV GOPATH /go
ENV PATH="${PATH}:/go/bin"

# gin to run reloading server
RUN go get github.com/codegangsta/gin

# add the source code
# currently this is handled by the docker run command
ADD ./server /go/src/letstalk/server

# install dep
RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

# set the working directory
WORKDIR /go/src/letstalk/server
RUN dep ensure

# install web dependencies
RUN yarn --cwd web install

# build web assets
RUN yarn --cwd web build

# fetch dependencies
ENV SECRETS_PATH secrets.json
