version: '3'
services:
  webapp:
    build: .
    ports:
      - "3000"
    volumes:
      - ./server:/go/src/letstalk/server
    depends_on:
      - db
    environment:
      - production=false
    networks:
      - db_net
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=uwletstalk
      - MYSQL_DATABASE=letstalk
      - MYSQL_USER=letstalk
      - MYSQL_PASSWORD=uwletstalk
    networks:
      - db_net
    ports:
      - "3306:3306"
volumes:
  dbdata:
networks:
  db_net:
