version: "3"
services:
  webapp:
    environment:
      - SECRETS_PATH=secrets.json
      - PROD=true
      - PORT=3000
  lb:
    restart: always
    ports:
      - "443:443"
    depends_on:
      - webapp
    volumes:
      - ./server/load_balancer/nginx.prod.conf:/etc/nginx/nginx.conf
      - "./landing:/var/app/hiveapp"
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/nginx_container/:/var/log/nginx
