# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
    working_directory: /go/src/letstalk
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run:
          name: Download dependency management software
          command: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run:
          name: Satisfy dependencies
          command: cd server && dep ensure
      - run:
          name: Run Go Tests!
          command: cd server && ./run_tests.sh
  js-tests:
    docker:
      - image: circleci/node:8.11.2-stretch
    working_directory: ~/var/app/letstalk
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd letstalk && yarn install
      - run:
          name: Run Tests
          command: cd letstalk && yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      # - build
      - js-tests
