// Code generated by ModelQ
// program.go contains model for the database table [letstalk.program]

package data

import (
	"database/sql"
	"encoding/gob"
	"encoding/json"
	"fmt"
	"github.com/mijia/modelq/gmq"
	"strings"
)

type Program struct {
	ProgramId string `json:"program_id"`
}

// Start of the Program APIs.

func (obj Program) String() string {
	if data, err := json.Marshal(obj); err != nil {
		return fmt.Sprintf("<Program ProgramId=%v>", obj.ProgramId)
	} else {
		return string(data)
	}
}

func (obj Program) Get(dbtx gmq.DbTx) (Program, error) {
	filter := ProgramObjs.FilterProgramId("=", obj.ProgramId)
	if result, err := ProgramObjs.Select().Where(filter).One(dbtx); err != nil {
		return obj, err
	} else {
		return result, nil
	}
}

func (obj Program) Insert(dbtx gmq.DbTx) (Program, error) {
	_, err := ProgramObjs.Insert(obj).Run(dbtx)
	return obj, err
}

func (obj Program) Update(dbtx gmq.DbTx) (int64, error) {
	fields := []string{}
	filter := ProgramObjs.FilterProgramId("=", obj.ProgramId)
	if result, err := ProgramObjs.Update(obj, fields...).Where(filter).Run(dbtx); err != nil {
		return 0, err
	} else {
		return result.RowsAffected()
	}
}

func (obj Program) Delete(dbtx gmq.DbTx) (int64, error) {
	filter := ProgramObjs.FilterProgramId("=", obj.ProgramId)
	if result, err := ProgramObjs.Delete().Where(filter).Run(dbtx); err != nil {
		return 0, err
	} else {
		return result.RowsAffected()
	}
}

// Start of the inner Query Api

type _ProgramQuery struct {
	gmq.Query
}

func (q _ProgramQuery) Where(f gmq.Filter) _ProgramQuery {
	q.Query = q.Query.Where(f)
	return q
}

func (q _ProgramQuery) OrderBy(by ...string) _ProgramQuery {
	tBy := make([]string, 0, len(by))
	for _, b := range by {
		sortDir := ""
		if b[0] == '-' || b[0] == '+' {
			sortDir = string(b[0])
			b = b[1:]
		}
		if col, ok := ProgramObjs.fcMap[b]; ok {
			tBy = append(tBy, sortDir+col)
		}
	}
	q.Query = q.Query.OrderBy(tBy...)
	return q
}

func (q _ProgramQuery) GroupBy(by ...string) _ProgramQuery {
	tBy := make([]string, 0, len(by))
	for _, b := range by {
		if col, ok := ProgramObjs.fcMap[b]; ok {
			tBy = append(tBy, col)
		}
	}
	q.Query = q.Query.GroupBy(tBy...)
	return q
}

func (q _ProgramQuery) Limit(offsets ...int64) _ProgramQuery {
	q.Query = q.Query.Limit(offsets...)
	return q
}

func (q _ProgramQuery) Page(number, size int) _ProgramQuery {
	q.Query = q.Query.Page(number, size)
	return q
}

func (q _ProgramQuery) Run(dbtx gmq.DbTx) (sql.Result, error) {
	return q.Query.Exec(dbtx)
}

type ProgramRowVisitor func(obj Program) bool

func (q _ProgramQuery) Iterate(dbtx gmq.DbTx, functor ProgramRowVisitor) error {
	return q.Query.SelectList(dbtx, func(columns []gmq.Column, rb []sql.RawBytes) bool {
		obj := ProgramObjs.toProgram(columns, rb)
		return functor(obj)
	})
}

func (q _ProgramQuery) One(dbtx gmq.DbTx) (Program, error) {
	var obj Program
	err := q.Query.SelectOne(dbtx, func(columns []gmq.Column, rb []sql.RawBytes) bool {
		obj = ProgramObjs.toProgram(columns, rb)
		return true
	})
	return obj, err
}

func (q _ProgramQuery) List(dbtx gmq.DbTx) ([]Program, error) {
	result := make([]Program, 0, 10)
	err := q.Query.SelectList(dbtx, func(columns []gmq.Column, rb []sql.RawBytes) bool {
		obj := ProgramObjs.toProgram(columns, rb)
		result = append(result, obj)
		return true
	})
	return result, err
}

func (q _ProgramQuery) Count(dbtx gmq.DbTx) (int, error) {
	result := 0

	err := q.Query.SelectCount(dbtx, func(columns []gmq.Column, rb []sql.RawBytes) bool {
		if len(columns) == len(rb) {
			for i := range columns {
				if "_count" == columns[i].Name {
					result = gmq.AsInt(rb[i])

					return true
				}
			}
		}

		return true
	})

	return result, err
}

// Start of the model facade Apis.

type _ProgramObjs struct {
	fcMap map[string]string
}

func (o _ProgramObjs) Names() (schema, tbl, alias string) {
	return "letstalk", "program", "Program"
}

func (o _ProgramObjs) Select(fields ...string) _ProgramQuery {
	q := _ProgramQuery{}
	if len(fields) == 0 {
		fields = []string{"ProgramId"}
	}
	q.Query = gmq.Select(o, o.columns(fields...))
	return q
}

func (o _ProgramObjs) Insert(obj Program) _ProgramQuery {
	q := _ProgramQuery{}
	q.Query = gmq.Insert(o, o.columnsWithData(obj, "ProgramId"))
	return q
}

func (o _ProgramObjs) Update(obj Program, fields ...string) _ProgramQuery {
	q := _ProgramQuery{}
	q.Query = gmq.Update(o, o.columnsWithData(obj, fields...))
	return q
}

func (o _ProgramObjs) Delete() _ProgramQuery {
	q := _ProgramQuery{}
	q.Query = gmq.Delete(o)
	return q
}

///// Managed Objects Filters definition

func (o _ProgramObjs) FilterProgramId(op string, p string, ps ...string) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("program_id", op, params...)
}

///// Managed Objects Columns definition

func (o _ProgramObjs) ColumnProgramId(p ...string) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"program_id", value}
}

////// Internal helper funcs

func (o _ProgramObjs) newFilter(name, op string, params ...interface{}) gmq.Filter {
	if strings.ToUpper(op) == "IN" {
		return gmq.InFilter(name, params)
	}
	return gmq.UnitFilter(name, op, params[0])
}

func (o _ProgramObjs) toProgram(columns []gmq.Column, rb []sql.RawBytes) Program {
	obj := Program{}
	if len(columns) == len(rb) {
		for i := range columns {
			switch columns[i].Name {
			case "program_id":
				obj.ProgramId = gmq.AsString(rb[i])
			}
		}
	}
	return obj
}

func (o _ProgramObjs) columns(fields ...string) []gmq.Column {
	data := make([]gmq.Column, 0, len(fields))
	for _, f := range fields {
		switch f {
		case "ProgramId":
			data = append(data, o.ColumnProgramId())
		}
	}
	return data
}

func (o _ProgramObjs) columnsWithData(obj Program, fields ...string) []gmq.Column {
	data := make([]gmq.Column, 0, len(fields))
	for _, f := range fields {
		switch f {
		case "ProgramId":
			data = append(data, o.ColumnProgramId(obj.ProgramId))
		}
	}
	return data
}

var ProgramObjs _ProgramObjs

func init() {
	ProgramObjs.fcMap = map[string]string{
		"ProgramId": "program_id",
	}
	gob.Register(Program{})
}
