// Code generated by ModelQ
// user_cohort.go contains model for the database table [letstalk.user_cohort]

package data

import (
	"database/sql"
	"encoding/gob"
	"encoding/json"
	"fmt"
	"github.com/mijia/modelq/gmq"
	"strings"
)

type UserCohort struct {
	UserId   int `json:"user_id"`
	CohortId int `json:"cohort_id"`
}

// Start of the UserCohort APIs.

func (obj UserCohort) String() string {
	if data, err := json.Marshal(obj); err != nil {
		return fmt.Sprintf("<UserCohort UserId=%v>", obj.UserId)
	} else {
		return string(data)
	}
}

func (obj UserCohort) Get(dbtx gmq.DbTx) (UserCohort, error) {
	filter := UserCohortObjs.FilterUserId("=", obj.UserId)
	if result, err := UserCohortObjs.Select().Where(filter).One(dbtx); err != nil {
		return obj, err
	} else {
		return result, nil
	}
}

func (obj UserCohort) Insert(dbtx gmq.DbTx) (UserCohort, error) {
	_, err := UserCohortObjs.Insert(obj).Run(dbtx)
	return obj, err
}

func (obj UserCohort) Update(dbtx gmq.DbTx) (int64, error) {
	fields := []string{"CohortId"}
	filter := UserCohortObjs.FilterUserId("=", obj.UserId)
	if result, err := UserCohortObjs.Update(obj, fields...).Where(filter).Run(dbtx); err != nil {
		return 0, err
	} else {
		return result.RowsAffected()
	}
}

func (obj UserCohort) Delete(dbtx gmq.DbTx) (int64, error) {
	filter := UserCohortObjs.FilterUserId("=", obj.UserId)
	if result, err := UserCohortObjs.Delete().Where(filter).Run(dbtx); err != nil {
		return 0, err
	} else {
		return result.RowsAffected()
	}
}

// Start of the inner Query Api

type _UserCohortQuery struct {
	gmq.Query
}

func (q _UserCohortQuery) Where(f gmq.Filter) _UserCohortQuery {
	q.Query = q.Query.Where(f)
	return q
}

func (q _UserCohortQuery) OrderBy(by ...string) _UserCohortQuery {
	tBy := make([]string, 0, len(by))
	for _, b := range by {
		sortDir := ""
		if b[0] == '-' || b[0] == '+' {
			sortDir = string(b[0])
			b = b[1:]
		}
		if col, ok := UserCohortObjs.fcMap[b]; ok {
			tBy = append(tBy, sortDir+col)
		}
	}
	q.Query = q.Query.OrderBy(tBy...)
	return q
}

func (q _UserCohortQuery) GroupBy(by ...string) _UserCohortQuery {
	tBy := make([]string, 0, len(by))
	for _, b := range by {
		if col, ok := UserCohortObjs.fcMap[b]; ok {
			tBy = append(tBy, col)
		}
	}
	q.Query = q.Query.GroupBy(tBy...)
	return q
}

func (q _UserCohortQuery) Limit(offsets ...int64) _UserCohortQuery {
	q.Query = q.Query.Limit(offsets...)
	return q
}

func (q _UserCohortQuery) Page(number, size int) _UserCohortQuery {
	q.Query = q.Query.Page(number, size)
	return q
}

func (q _UserCohortQuery) Run(dbtx gmq.DbTx) (sql.Result, error) {
	return q.Query.Exec(dbtx)
}

type UserCohortRowVisitor func(obj UserCohort) bool

func (q _UserCohortQuery) Iterate(dbtx gmq.DbTx, functor UserCohortRowVisitor) error {
	return q.Query.SelectList(dbtx, func(columns []gmq.Column, rb []sql.RawBytes) bool {
		obj := UserCohortObjs.toUserCohort(columns, rb)
		return functor(obj)
	})
}

func (q _UserCohortQuery) One(dbtx gmq.DbTx) (UserCohort, error) {
	var obj UserCohort
	err := q.Query.SelectOne(dbtx, func(columns []gmq.Column, rb []sql.RawBytes) bool {
		obj = UserCohortObjs.toUserCohort(columns, rb)
		return true
	})
	return obj, err
}

func (q _UserCohortQuery) List(dbtx gmq.DbTx) ([]UserCohort, error) {
	result := make([]UserCohort, 0, 10)
	err := q.Query.SelectList(dbtx, func(columns []gmq.Column, rb []sql.RawBytes) bool {
		obj := UserCohortObjs.toUserCohort(columns, rb)
		result = append(result, obj)
		return true
	})
	return result, err
}

func (q _UserCohortQuery) Count(dbtx gmq.DbTx) (int, error) {
	result := 0

	err := q.Query.SelectCount(dbtx, func(columns []gmq.Column, rb []sql.RawBytes) bool {
		if len(columns) == len(rb) {
			for i := range columns {
				if "_count" == columns[i].Name {
					result = gmq.AsInt(rb[i])

					return true
				}
			}
		}

		return true
	})

	return result, err
}

// Start of the model facade Apis.

type _UserCohortObjs struct {
	fcMap map[string]string
}

func (o _UserCohortObjs) Names() (schema, tbl, alias string) {
	return "letstalk", "user_cohort", "UserCohort"
}

func (o _UserCohortObjs) Select(fields ...string) _UserCohortQuery {
	q := _UserCohortQuery{}
	if len(fields) == 0 {
		fields = []string{"UserId", "CohortId"}
	}
	q.Query = gmq.Select(o, o.columns(fields...))
	return q
}

func (o _UserCohortObjs) Insert(obj UserCohort) _UserCohortQuery {
	q := _UserCohortQuery{}
	q.Query = gmq.Insert(o, o.columnsWithData(obj, "UserId", "CohortId"))
	return q
}

func (o _UserCohortObjs) Update(obj UserCohort, fields ...string) _UserCohortQuery {
	q := _UserCohortQuery{}
	q.Query = gmq.Update(o, o.columnsWithData(obj, fields...))
	return q
}

func (o _UserCohortObjs) Delete() _UserCohortQuery {
	q := _UserCohortQuery{}
	q.Query = gmq.Delete(o)
	return q
}

///// Managed Objects Filters definition

func (o _UserCohortObjs) FilterUserId(op string, p int, ps ...int) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("user_id", op, params...)
}

func (o _UserCohortObjs) FilterCohortId(op string, p int, ps ...int) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("cohort_id", op, params...)
}

///// Managed Objects Columns definition

func (o _UserCohortObjs) ColumnUserId(p ...int) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"user_id", value}
}

func (o _UserCohortObjs) ColumnCohortId(p ...int) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"cohort_id", value}
}

////// Internal helper funcs

func (o _UserCohortObjs) newFilter(name, op string, params ...interface{}) gmq.Filter {
	if strings.ToUpper(op) == "IN" {
		return gmq.InFilter(name, params)
	}
	return gmq.UnitFilter(name, op, params[0])
}

func (o _UserCohortObjs) toUserCohort(columns []gmq.Column, rb []sql.RawBytes) UserCohort {
	obj := UserCohort{}
	if len(columns) == len(rb) {
		for i := range columns {
			switch columns[i].Name {
			case "user_id":
				obj.UserId = gmq.AsInt(rb[i])
			case "cohort_id":
				obj.CohortId = gmq.AsInt(rb[i])
			}
		}
	}
	return obj
}

func (o _UserCohortObjs) columns(fields ...string) []gmq.Column {
	data := make([]gmq.Column, 0, len(fields))
	for _, f := range fields {
		switch f {
		case "UserId":
			data = append(data, o.ColumnUserId())
		case "CohortId":
			data = append(data, o.ColumnCohortId())
		}
	}
	return data
}

func (o _UserCohortObjs) columnsWithData(obj UserCohort, fields ...string) []gmq.Column {
	data := make([]gmq.Column, 0, len(fields))
	for _, f := range fields {
		switch f {
		case "UserId":
			data = append(data, o.ColumnUserId(obj.UserId))
		case "CohortId":
			data = append(data, o.ColumnCohortId(obj.CohortId))
		}
	}
	return data
}

var UserCohortObjs _UserCohortObjs

func init() {
	UserCohortObjs.fcMap = map[string]string{
		"UserId":   "user_id",
		"CohortId": "cohort_id",
	}
	gob.Register(UserCohort{})
}
